### Registra un usuario
# para pruebas solo cambia el correo 1,2,3...
POST http://127.0.0.1:5566/user HTTP/1.1
Content-Type: application/json

{
"user_name": "usuario",
"user_email": "11@example.com",
"user_pass": "pass"
}

### Inicia sesión
POST http://127.0.0.1:5566/signin HTTP/1.1
Content-Type: application/json

{
"user_email": "9@example.com",
"user_pass": "pass"
}

### Cambia el plan del usuario, independientemente si tiene o no un plan.
# 1-plus 2-pro
POST http://127.0.0.1:5566/plan HTTP/1.1
Content-Type: application/json

{
 "user_id": "ec91bfd9-471c-4d5a-b120-f85c5c79d937",
 "plan": 1   
}

### TTS plus users
POST http://127.0.0.1:5566/plustts HTTP/1.1
Content-Type: application/json

{
    "text" : "The old lighthouse keeper, Silas Blackwood, had seen countless storms rage across the turbulent waters of the Gulf of Guacamayas. For seventy-seven years, the rhythmic pulse of the beacon had been his constant companion, a steadfast sentinel against the capricious moods of the ocean. He remembered the fierce hurricane of '98, a roaring beast that clawed at the stone tower with relentless fury, threatening to swallow it whole. The waves, colossal and unforgiving, crashed against the rocky coastline, sending plumes of saltwater high into the inky sky. Even the seasoned fishermen of Guacamayas, men who knew the sea like the back of their weathered hands, had sought refuge, their colorful boats bobbing precariously in the sheltered harbor."
}


### ojn

POST http://localhost:5566/protts
Content-Type: multipart/form-data; boundary=----MyRestClientBoundary

------MyRestClientBoundary
Content-Disposition: form-data; name="file1"; filename="a.txt"
# Optional: Specify Content-Type if known, otherwise REST Client might guess
# Content-Type: text/plain

< ./a.txt

------MyRestClientBoundary
Content-Disposition: form-data; name="file2"; filename="b.txt"
# Content-Type: text/plain

< ./b.txt

------MyRestClientBoundary--