### Registra un usuario
# para pruebas solo cambia el correo 1,2,3...
POST http://127.0.0.1:5566/user HTTP/1.1
Content-Type: application/json

{
"user_name": "usuario",
"user_email": "9@example.com",
"user_pass": "pass"
}

### Inicia sesión
POST http://127.0.0.1:5566/signin HTTP/1.1
Content-Type: application/json

{
"user_email": "9@example.com",
"user_pass": "pass"
}

### Cambia el plan del usuario, independientemente si tiene o no un plan.
# 1-plus 2-pro
POST http://127.0.0.1:5566/plan HTTP/1.1
Content-Type: application/json

{
 "user_id": "3b03bae4-23cd-438b-a7b6-21af672bbfea",
 "plan": 1   
}